### ISSUE TITLE
make doesn't run

### ISSUE THREAD

**Issue by sbatllori** [pierrextardif/ofxPlasticTexture#1]
Hello!

I juts wanted to try out your addon by downloading your repo and puting it into my OF/addons folder. However, I found a problem when I try to `make` the example from the OF/addons/ofxPlasticTexture/example folder. `make` throws the following error:
```bash
Makefile:13: ../../../libs/openFrameworksCompiled/project/makefileCommon/config.project.make: No such file or directory
```
and line 13 looks like this:
```bash
include $(OF_ROOT)/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
```

I fixed it by replacing your Makefile with the one that's automatically generated by OF with the project generator. For me replacing line 13 with the following one worked out:
```bash
include $(OF_ROOT)/libs/openFrameworksCompiled/project/makefileCommon/config.project.make
```

Did you change the word `config` for `compile` for any specific reason or it's just a writing mistake?

Thanks a lot!

**Comment by pierrextardif** [comment]
Hi, 

Ah yeah I am using macOS,

Try using the empty example from myApps, and import the correct elements in to the sketch.

So in ofApp.h :
```


#include "ofxPlasticTexture.hpp"

class ofApp : public ofBaseApp{

	public:

		void setup();
		void update();
		void draw();
    
        void keyPressed(int key);
    
    
    ofxPlasticTexture plastic;
```
in ofApp.cpp :
```

//--------------------------------------------------------------
void ofApp::setup()
{
	ofSetLogLevel(OF_LOG_VERBOSE);
    plastic.setup();
    
    
}

//--------------------------------------------------------------
void ofApp::update()
{
    
   
}

//--------------------------------------------------------------
void ofApp::draw()
{
    plastic.begin();
//    ofSetColor(255, 20, 120);
    
    plastic.end();
    
}

//--------------------------------------------------------------
void ofApp::keyPressed(int key) {
    
    if(key == ' ')plastic.updateTexture();
    if(key == 'r')plastic.resetTextureOffset();
    if(key == 'm')plastic.moveTexture();
}
```

Make sure you have setup the openGL version in main.cpp :
```

    ofGLWindowSettings settings;
//    settings.setSize(1080, 1350);
    settings.setSize(2000, 1000);
    settings.setGLVersion(3,2);
    ofCreateWindow(settings);
    
    
	ofRunApp( new ofApp());
```

Let me know if it works,

++

P

**Comment by pierrextardif** [comment]
The macOS makefile is different, hence the error...

**Comment by sbatllori** [comment]
Aha! Yes, OK! It works, thank you very much!
